[23:58:20.558251] Model params:
 {
    "inv_weight": 0.2,
    "kl_weight": 0.005,
    "layer_depth": 8,
    "part_latents_dim": 128,
    "rec_weight": 0.8
}
[23:58:20.559846] Start training for [500] epochs, from epoch [0].
[23:58:23.127831] [23:58:23.128507] [23:58:23.129255] [23:58:23.129785] [23:58:23.130352] [23:58:23.130801] [23:58:23.131108] [23:58:23.131614]
Traceback (most recent call last):
  File "/ibex/user/slimhy/PADS/code/main_partvae.py", line 398, in <module>
    main(args)
  File "/ibex/user/slimhy/PADS/code/main_partvae.py", line 375, in main
    train_model(
  File "/ibex/user/slimhy/PADS/code/main_partvae.py", line 240, in train_model
    train_stats = train_one_epoch(
  File "/ibex/user/slimhy/PADS/code/engine_partvae.py", line 109, in train_one_epoch
    loss = forward_pass(
  File "/ibex/user/slimhy/PADS/code/engine_partvae.py", line 57, in forward_pass
    rec_loss = F.mse_loss(logits_a, l_a) + F.mse_loss(logits_b, l_b)
  File "/home/slimhy/conda/envs/3D2VS_flexicubes/lib/python3.10/site-packages/torch/nn/functional.py", line 3295, in mse_loss
    return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!